// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({ children }) {
//   return (
//     <html lang="en">
//       <body
//         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
//       >
//         {children}
//       </body>
//     </html>
//   );
// }

// app/layout.js
import './globals.css';
import React from 'react';

export const metadata = {
  title: 'Safe Sense',
  description: 'Sensor-based refrigeration monitoring',
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <header style={styles.header}>
          <div style={styles.logo}>Safe Sense</div>
        </header>

        <main style={styles.main}>
          {children}
        </main>

        <footer style={styles.footer}>
          © {new Date().getFullYear()} Safe Sense. All rights reserved.
        </footer>
      </body>
    </html>
  );
}

const styles = {
  header: {
    display: 'flex',
    justifyContent: 'space-between',
    padding: '1rem 2rem',
    backgroundColor: '#f0f0f0',
    borderBottom: '1px solid #ccc',
    fontWeight: 'bold'
  },
  logo: {
    fontSize: '1.5rem',
  },
  main: {
    minHeight: '80vh',
    padding: '2rem',
  },
  footer: {
    padding: '1rem 2rem',
    backgroundColor: '#f0f0f0',
    borderTop: '1px solid #ccc',
    textAlign: 'center',
  }
};

